# Generated by Django 2.2.2 on 2019-08-19 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportclub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportclubmodel',
            name='bankaccount_shabanumber',
        ),
    ]
