# Generated by Django 2.2.2 on 2019-07-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonmodel',
            name='profit_percantage',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
