# Generated by Django 2.2.2 on 2019-07-26 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_salonmodel_profit_percantage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salonmodel',
            old_name='profit_percantage',
            new_name='profit_percentage',
        ),
    ]
