# Generated by Django 2.2.2 on 2019-07-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_auto_20190727_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonmodel',
            name='profit_percentage',
            field=models.IntegerField(),
        ),
    ]
