# Generated by Django 2.2.2 on 2019-08-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_auto_20190727_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonmodel',
            name='buffet',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salonmodel',
            name='local_taxi',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salonmodel',
            name='wifi',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salonmodel',
            name='changing_room',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='salonmodel',
            name='shower',
            field=models.BooleanField(),
        ),
    ]
