# Generated by Django 2.2.2 on 2019-08-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_auto_20190807_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonmodel',
            name='is_handball',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
