# Generated by Django 2.2.2 on 2019-08-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_salonmodel_is_handball'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonmodel',
            name='air_conditioner',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salonmodel',
            name='ball_rent',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salonmodel',
            name='spectator_place',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
