# Generated by Django 2.2.2 on 2019-08-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_auto_20190809_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonmodel',
            name='area',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='salonmodel',
            name='profit_percentage',
            field=models.PositiveIntegerField(),
        ),
    ]
