# Generated by Django 2.2.2 on 2019-09-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmodel',
            name='day_str',
            field=models.CharField(default='1398-03-20', max_length=264),
            preserve_default=False,
        ),
    ]
