# Generated by Django 2.2.2 on 2019-07-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastdatamodel',
            name='last_friday_2',
        ),
        migrations.RemoveField(
            model_name='lastdatamodel',
            name='last_monday_2',
        ),
        migrations.RemoveField(
            model_name='lastdatamodel',
            name='last_saturday_2',
        ),
        migrations.RemoveField(
            model_name='lastdatamodel',
            name='last_sunday_2',
        ),
        migrations.RemoveField(
            model_name='lastdatamodel',
            name='last_thursday_2',
        ),
        migrations.RemoveField(
            model_name='lastdatamodel',
            name='last_tuesday_2',
        ),
        migrations.RemoveField(
            model_name='lastdatamodel',
            name='last_wednesday_2',
        ),
        migrations.AlterField(
            model_name='lastdatamodel',
            name='last_friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lastdatamodel',
            name='last_monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lastdatamodel',
            name='last_saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lastdatamodel',
            name='last_sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lastdatamodel',
            name='last_thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lastdatamodel',
            name='last_tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lastdatamodel',
            name='last_wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
