# Generated by Django 2.2.2 on 2019-07-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20190718_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncategorymodel',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
