# Generated by Django 2.2.2 on 2019-07-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_sessioncategorymodel_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmodel',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
