# Generated by Django 2.2.2 on 2019-08-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_sessionmodel_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmodel',
            name='booking_code',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
