# Generated by Django 2.2.2 on 2019-07-26 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('session', '0003_sessioncategorymodel_is_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_percantage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateTimeField()),
                ('price', models.IntegerField()),
                ('profit_percantage', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='session.SessionModel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
