# Generated by Django 2.2.2 on 2019-09-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmodel',
            name='str_created_at_date',
            field=models.CharField(default='1398-07-25', max_length=264),
            preserve_default=False,
        ),
    ]
