# Generated by Django 2.2.2 on 2019-09-16 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190915_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.ContractModel'),
        ),
    ]
