# Generated by Django 2.2.2 on 2019-08-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190727_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingmodel',
            old_name='date',
            new_name='datetime',
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='cancelled',
            field=models.BooleanField(default=True),
        ),
    ]
