# Generated by Django 2.2.2 on 2019-09-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bookingmodel_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmodel',
            name='company_portion',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='sportclub_portion',
            field=models.FloatField(null=True),
        ),
    ]
