# Generated by Django 2.2.2 on 2019-09-02 11:04

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_condition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReckoningModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfered_at_date', django_jalali.db.models.jDateField(null=True)),
                ('transfered_at_time', models.TimeField(null=True)),
                ('money_transfered', models.FloatField()),
                ('salon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reckonings', to='salon.SalonModel')),
            ],
        ),
    ]
