# Generated by Django 2.2.2 on 2019-09-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reckoningmodel',
            name='str_transfered_at_date',
            field=models.CharField(default='1398-05-26', max_length=264),
            preserve_default=False,
        ),
    ]
