# Generated by Django 2.2.2 on 2019-09-06 00:06

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
        ('company', '0002_reckoningmodel_str_transfered_at_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonAdvertisementModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at_date', django_jalali.db.models.jDateField(null=True)),
                ('str_added_at_date', models.CharField(max_length=264)),
                ('added_at_time', models.TimeField(null=True)),
                ('salon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisements', to='salon.SalonModel')),
            ],
        ),
    ]
